name: Release Details

on:
  release:
    types: [published]

jobs:
  print_release_details:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      RELEASE_DATE: ${{ github.event.release.published_at }}
    steps:
      - name: Print Release Details
        run: |
           echo "export RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
           echo "export RELEASE_DATE=${{ github.event.release.published_at }}" >> $GITHUB_ENV
     
      -  name: Set up Python
         uses: actions/setup-python@v2
         with:
          python-version: '3.x'
          
      - name: Run Python script
        run: python3 Test/test.py
