name: Release Details

on:
  release:
    types: [published]

jobs:
  print_release_details:
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Details
        run: |
          echo "Tag Name: ${{ github.event.release.tag_name }}"
          echo "Published At: ${{ github.event.release.published_at }}"
